name: ci-create-sonik
on:
  push:
    branches: [main]
    paths:
      - 'packages/create-sonik/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/create-sonik/**'
jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/create-sonik
    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
